#!/bin/sh
#
# Wrapper for running Bakefile using system's Python version
#

prefix="@prefix@"
program="`basename $0`"

python="/usr/bin/python"
pyver=`"$python" -c "from distutils import sysconfig; print sysconfig.get_python_version()"`

PYTHONPATH="$prefix/lib/bakefile/binmodules/$pyver:$PYTHONPATH"
export PYTHONPATH

exec "$python" "$prefix/lib/bakefile/$program.py" "$@"
