#!/bin/sh
#
# Wrapper for running Bakefile using system's Python version
#

prefix="@prefix@"
python=python
program="`basename $0`"
pyver=`"$python" -c "from distutils import sysconfig; print sysconfig.get_python_version()"`

PYTHONPATH="$prefix/lib/bakefile/binmodules/$pyver:$PYTHONPATH"
export PYTHONPATH

"$python" "$prefix/lib/bakefile/$program.py" "$@"
