#!/bin/sh

TESTS="dll hello library cond"

aclocal -I dll -I ../autoconf
autoconf

../src/bakefile.py -f autoconf -o Makefile.in root.bakefile

for t in $TESTS ; do
    echo $t
    cd $t
    ../../src/bakefile.py -f autoconf -o Makefile.in *.bakefile
    cd ..
done
