# CI workflow running the unit tests.
name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    # We need to use an OS old enough to still have Python 2
    container: ubuntu:22.04

    steps:
    - name: Set up
      run: |
        apt-get update -qq
        apt-get install -qq curl default-jre git make python2
        curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
        python2 get-pip.py

    - name: Check out
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pip install Sphinx
        pip install pytest
        pip install clint

    - name: Run tests
      run: make test
